- name: rpi
  hosts: rpi
  become: yes
  remote_user: ansible
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
  roles:
  - node-exporter
  - consul-agent
  - zfs-exporter

- name: My first play
  hosts: all
  become: yes
  remote_user: ansible
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
   - name: install apt packages
     ansible.builtin.apt:
       pkg:
       - lshw
       - fail2ban
       - tmux
       update_cache: yes
   - name: Install zfsutils-linux with ensuring conflicted packages (e.g. zfs-fuse) will not be removed.
     ansible.builtin.apt:
       name: zfsutils-linux
       state: latest

   - name: Start fail2ban service
     service:
       name: fail2ban
       state: started
     become: true

   - name: Enable fail2ban service
     service:
       name: fail2ban
       enabled: true
     become: true

- name: install node-exporter
  hosts: all
  become: yes
  remote_user: ansible
  roles:
#  - node-exporter
  - consul-agent
  - zfs-exporter
