---
- name: Create Configuration Directories
  ansible.builtin.file:
    path: /etc/consul.d
    mode: 0755
    state: directory

- name: Create Consul Directory
  ansible.builtin.file:
    path: /opt/consul/bin
    mode: 0755
    state: directory

- name: Check Version Installed
  ansible.builtin.shell: |
         set -o pipefail
         if [ -f /opt/consul/bin/consul ]; then
             /opt/consul/bin/consul --version|awk 'NR==1{print $2}' |cut -dv -f2
         fi
  args:
    executable: /bin/bash
  register: consul_version_check
  changed_when: consul_version_check.stdout != consul_version

- name: Ensure dependencies are present
  package:
    name: 'unzip'
    state: "present"

- name: Download Consul Software
  ansible.builtin.unarchive:
    src: "{{ consul_zip_url }}"
    dest: /opt/consul/bin
    remote_src: yes
    mode: 0755
  when: consul_version_check.stdout != consul_version
  notify:
    - restart consul

- name: Copy client Config
  copy:
    content: "{{ consul_client_conf | to_json }}"
    dest: /etc/consul.d/config.json
    mode: 0644
    backup: yes
  notify:
    - reload consul

- name: Copy service configs
  copy:
    dest: /etc/consul.d/{{ item.service.name }}.json
    mode: 0644
    content: "{{ item | to_json }}"
  loop: "{{ consul_service_list }}"
  notify:
    - reload consul

- name: Copy systemd unit file
  ansible.builtin.template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: "root"
    group: "root"
    mode: 0644
    backup: no

- name: start consul
  systemd: state=started enabled=yes name=consul daemon_reload=yes
