---
- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: reload consul
  systemd:
    name: consul.service
    state: reloaded

- name: restart consul
  systemd:
    name: consul.service
    state: restarted

- name: enable consul
  ansible.builtin.service:
    name: consul
    enabled: yes
